# Generated by Django 4.1 on 2022-08-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('parent_community', models.CharField(blank=True, max_length=100)),
                ('short_description', models.TextField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
